// Mocks generated by Mockito 5.4.4 from annotations
// in breizh_blok_mobile/test/unit/models/boulder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:breizh_blok_mobile/models/boulder_area.dart' as _i2;
import 'package:breizh_blok_mobile/models/location.dart' as _i3;
import 'package:breizh_blok_mobile/models/rock.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBoulderArea_0 extends _i1.SmartFake implements _i2.BoulderArea {
  _FakeBoulderArea_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocation_1 extends _i1.SmartFake implements _i3.Location {
  _FakeLocation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Rock].
///
/// See the documentation for Mockito's code generation for more information.
class MockRock extends _i1.Mock implements _i4.Rock {
  MockRock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);
  @override
  String get iri => (super.noSuchMethod(
        Invocation.getter(#iri),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#iri),
        ),
      ) as String);
  @override
  _i2.BoulderArea get boulderArea => (super.noSuchMethod(
        Invocation.getter(#boulderArea),
        returnValue: _FakeBoulderArea_0(
          this,
          Invocation.getter(#boulderArea),
        ),
      ) as _i2.BoulderArea);
  @override
  _i3.Location get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _FakeLocation_1(
          this,
          Invocation.getter(#location),
        ),
      ) as _i3.Location);
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}
