include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - test/**/*.mocks.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/i18n/app_localizations_*.dart"
  errors:
    invalid_annotation_target: ignore