name: breizh_blok

packages:
  - packages/*
  - tools/*

sdkPath: .fvm/flutter_sdk

scripts:
  build_runner:
    run: dart run melos exec --fail-fast --order-dependents -- "dart run build_runner build --delete-conflicting-outputs"
    description: Generate files in melos workspace
    packageFilters:
      dependsOn: build_runner
 
  analyze:
    run: dart run melos exec --concurrency=1 --fail-fast -- "dart analyze . --fatal-infos"
    description: Run Dart analyze in all dart packages.
 
  test:
    run: dart run melos exec --concurrency=1 --fail-fast -- "flutter test --test-randomize-ordering-seed random"
    description: Run tests.
    packageFilters:
      flutter: true
      dirExists: test

  test:ci:
    run: dart run melos exec --concurrency=1 --fail-fast -- "flutter test --coverage --test-randomize-ordering-seed random"
    description: Run tests.
    packageFilters:
      flutter: true
      dirExists: test

  generate:breizh_blok_api:
    run: |
      set -e
      rm -rf packages/breizh_blok_api_generated/lib && rm -rf packages/breizh_blok_api_generated/doc
      docker run --rm \
      -v ${PWD}:/project openapitools/openapi-generator-cli generate \
      -i /project/openapi/breizh_blok_api/openapi.json \
      -c /project/openapi/breizh_blok_api/config.json \
      -g dart-dio \
      -o /project/packages/breizh_blok_api_generated

      dart run melos exec --scope="breizh_blok_api_generated" -- "dart run build_runner build --delete-conflicting-outputs"
      dart run melos exec --scope="breizh_blok_api_generated" -- "dart format ."
      dart run melos exec --scope="breizh_blok_api_generated" -- "dart fix --apply ."