name: breizh_blok

packages:
  - packages/*
  - tools/*

sdkPath: .fvm/flutter_sdk

scripts:
  build_runner:
    run: dart run melos exec --fail-fast --order-dependents -- "dart run build_runner build --delete-conflicting-outputs"
    description: Generate files in melos workspace
    packageFilters:
      dependsOn: build_runner
 
  analyze:
    run: dart run melos exec --concurrency=1 --fail-fast -- "dart analyze . --fatal-infos"
    description: Run Dart analyze in all dart packages.
 
  test:
    run: dart run melos exec --concurrency=1 --fail-fast -- "flutter test"
    description: Run tests.
    packageFilters:
      flutter: true
      dirExists: test