sonar.projectKey=jeremyriverain_breizh-blok-mobile
sonar.organization=jeremyriverain

sonar.sources=packages/app/lib,packages/auth/lib
sonar.tests=packages/app/test,packages/auth/test

sonar.sourceEncoding=UTF-8

sonar.exclusions=packages/*/test/**/*_test.mocks.dart,packages/*/lib/**/*.g.dart