// Mocks generated by Mockito 5.4.5 from annotations
// in breizh_blok_mobile/test/ui/download/view_models/downloaded_boulder_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:breizh_blok_mobile/data/data_sources/api/api_client.dart'
    as _i3;
import 'package:breizh_blok_mobile/data/data_sources/local/app_database.dart'
    as _i2;
import 'package:breizh_blok_mobile/data/repositories/downloaded_boulder_repository/downloaded_boulder_repository.dart'
    as _i5;
import 'package:breizh_blok_mobile/domain/models/boulder/boulder.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiClient_1 extends _i1.SmartFake implements _i3.ApiClient {
  _FakeApiClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBoulder_2 extends _i1.SmartFake implements _i4.Boulder {
  _FakeBoulder_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadedBoulderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadedBoulderRepository extends _i1.Mock
    implements _i5.DownloadedBoulderRepository {
  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#database),
            ),
          )
          as _i2.AppDatabase);
  @override
  _i3.ApiClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeApiClient_1(this, Invocation.getter(#httpClient)),
            returnValueForMissingStub: _FakeApiClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i3.ApiClient);
  @override
  _i6.Future<_i4.Boulder> find({
    required String? boulderAreaIri,
    required String? boulderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#find, [], {
              #boulderAreaIri: boulderAreaIri,
              #boulderId: boulderId,
            }),
            returnValue: _i6.Future<_i4.Boulder>.value(
              _FakeBoulder_2(
                this,
                Invocation.method(#find, [], {
                  #boulderAreaIri: boulderAreaIri,
                  #boulderId: boulderId,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Boulder>.value(
              _FakeBoulder_2(
                this,
                Invocation.method(#find, [], {
                  #boulderAreaIri: boulderAreaIri,
                  #boulderId: boulderId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Boulder>);
}
