targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
      - integration_test/**.dart
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
          - integration_test/**.dart