// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dbRequests,
    dbBoulderAreas,
    gradeTable,
  ];
  late final Shape0 dbRequests = Shape0(
    source: i0.VersionedTable(
      entityName: 'db_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(request_path)'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 dbBoulderAreas = Shape1(
    source: i0.VersionedTable(
      entityName: 'db_boulder_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gradeTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'grade_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get requestPath =>
      columnsByName['request_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get responseBody =>
      columnsByName['response_body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'request_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'response_body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get iri =>
      columnsByName['iri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get downloadProgress =>
      columnsByName['download_progress']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get boulders =>
      columnsByName['boulders']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadedAt =>
      columnsByName['downloaded_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'iri',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'download_progress',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'boulders',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES db_requests(request_path)',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'downloaded_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const i1.CustomExpression('CURRENT_TIMESTAMP'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get iri =>
      columnsByName['iri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dbRequests,
    dbBoulderAreas,
    gradeTable,
    boulderGeoPointTable,
  ];
  late final Shape0 dbRequests = Shape0(
    source: i0.VersionedTable(
      entityName: 'db_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(request_path)'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 dbBoulderAreas = Shape1(
    source: i0.VersionedTable(
      entityName: 'db_boulder_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gradeTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'grade_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 boulderGeoPointTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'boulder_geo_point_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_7, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lng =>
      columnsByName['lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get areaId =>
      columnsByName['area_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lng',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'area_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dbRequests,
    dbBoulderAreas,
    gradeTable,
    boulderGeoPointTable,
    area,
  ];
  late final Shape0 dbRequests = Shape0(
    source: i0.VersionedTable(
      entityName: 'db_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(request_path)'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 dbBoulderAreas = Shape1(
    source: i0.VersionedTable(
      entityName: 'db_boulder_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gradeTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'grade_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 boulderGeoPointTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'boulder_geo_point_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_7, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index area = i1.Index(
    'area',
    'CREATE INDEX area ON boulder_geo_point_table (area_id)',
  );
}

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    boulderGeoPointTable,
    dbRequests,
    dbBoulderAreas,
    departmentTable,
    gradeTable,
    municipalityTable,
    area,
  ];
  late final Shape3 boulderGeoPointTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'boulder_geo_point_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_7, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 dbRequests = Shape0(
    source: i0.VersionedTable(
      entityName: 'db_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(request_path)'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 dbBoulderAreas = Shape1(
    source: i0.VersionedTable(
      entityName: 'db_boulder_areas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 departmentTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'department_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_11],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gradeTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'grade_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 municipalityTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'municipality_table',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(iri)'],
      columns: [_column_2, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index area = i1.Index(
    'area',
    'CREATE INDEX area ON boulder_geo_point_table (area_id)',
  );
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get iri =>
      columnsByName['iri']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get department =>
      columnsByName['department']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'department',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES department_table(iri)',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
