name: Install Flutter Environment
description: Setup Flutter SDK and install dependencies
runs:
  using: "composite"
  steps:
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
    - name: Install dependencies
      run: flutter pub get
      shell: bash
