// Mocks generated by Mockito 5.4.4 from annotations
// in breizh_blok_mobile/test/ui/core/widgets/share_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:breizh_blok_mobile/services/share_content/share_content_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:share_plus/share_plus.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShareResult_0 extends _i1.SmartFake implements _i2.ShareResult {
  _FakeShareResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShareContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareContentService extends _i1.Mock
    implements _i3.ShareContentService {
  @override
  _i4.Future<_i2.ShareResult> share(String? text) => (super.noSuchMethod(
        Invocation.method(
          #share,
          [text],
        ),
        returnValue: _i4.Future<_i2.ShareResult>.value(_FakeShareResult_0(
          this,
          Invocation.method(
            #share,
            [text],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ShareResult>.value(_FakeShareResult_0(
          this,
          Invocation.method(
            #share,
            [text],
          ),
        )),
      ) as _i4.Future<_i2.ShareResult>);
}
