// Mocks generated by Mockito 5.4.2 from annotations
// in breizh_blok_mobile/test/unit/download_area_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:breizh_blok_mobile/image_boulder_cache.dart' as _i3;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCacheManager_0 extends _i1.SmartFake implements _i2.CacheManager {
  _FakeCacheManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImageBoulderCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageBoulderCache extends _i1.Mock implements _i3.ImageBoulderCache {
  @override
  _i2.CacheManager get cache => (super.noSuchMethod(
        Invocation.getter(#cache),
        returnValue: _FakeCacheManager_0(
          this,
          Invocation.getter(#cache),
        ),
        returnValueForMissingStub: _FakeCacheManager_0(
          this,
          Invocation.getter(#cache),
        ),
      ) as _i2.CacheManager);
}
