name: 🚀 Distribute on Test Flight

on:
  workflow_dispatch: ~

jobs:
  distribute_test_flight:
    name: Distribute on Test Flight
    runs-on: macos-15
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - name: Build runner
        env:
          BREIZH_BLOK_API_HOST: ${{secrets.BREIZH_BLOK_API_HOST_RELEASE}}
          BREIZH_BLOK_API_SCHEME: ${{secrets.BREIZH_BLOK_API_SCHEME_RELEASE}}
          BREIZH_BLOK_API_PORT: ${{secrets.BREIZH_BLOK_API_PORT_RELEASE}}
          BREIZH_BLOK_AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          BREIZH_BLOK_AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          BREIZH_BLOK_MAPBOX_TOKEN: ${{secrets.MAPBOX_TOKEN_RELEASE}}
          BREIZH_BLOK_MIX_PANEL_TOKEN: ${{secrets.BREIZH_BLOK_MIX_PANEL_TOKEN_RELEASE}}
          BREIZH_BLOK_SENTRY_URL: ${{secrets.BREIZH_BLOK_SENTRY_DSN_RELEASE}}
        run: dart run melos run build_runner --no-select

      - name: Set Keychain path
        run: echo "KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db" >> $GITHUB_ENV

      - name: Create keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $KEYCHAIN_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security default-keychain -s $KEYCHAIN_PATH

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: distribute
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          set -e
          cd packages/app
          flutter doctor --verbose
          cd ios
          touch .env.local
          echo "APPLE_ID=${{secrets.APPLE_ID}}" > .env.local
          touch gc_keys.json
          echo ${{ secrets.FASTLANE_GOOGLE_SERVICE_ACCOUNT }} | base64 -d > gc_keys.json
          bundle install && bundle exec fastlane certificates

          cd ../

          build_number="$(date +%s)"
          echo "build-number: $build_number"

          mkdir -p ~/private_keys
          echo ${{ secrets.APPLE_STORE_PRIVATE_KEY }} | base64 -d > ~/private_keys/AuthKey_${{secrets.APP_STORE_API_KEY_ID}}.p8

          flutter build ipa \
            --verbose \
            --build-number=$build_number \
            --release \
            --export-options-plist=ios/buildInfo.plist \
            --obfuscate \
            --split-debug-info=symbols \
            --extra-gen-snapshot-options=--save-obfuscation-map=obfuscation.map.json

          xcrun altool --upload-app --type ios -f build/ios/ipa/Breizh\ Blok.ipa --apiKey "${{secrets.APP_STORE_API_KEY_ID}}" --apiIssuer "${{secrets.APP_STORE_API_KEY_ISSUER_ID}}"

      - name: Sentry upload debug symbols
        env:
          SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
          SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        run: |
          dart run melos exec --scope="breizh_blok_mobile" -- dart run sentry_dart_plugin
